"""bleepblorp

Revision ID: 601de21a505d
Revises: 3c26510ff7ac
Create Date: 2021-12-09 22:48:39.727080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601de21a505d'
down_revision = '3c26510ff7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', '_linkHash',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', '_linkHash',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
