"""anuddahOne1

Revision ID: 7cd291f95267
Revises: b9eaa2c3d0bc
Create Date: 2021-12-09 23:10:34.498552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd291f95267'
down_revision = 'b9eaa2c3d0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', '_linkHash',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', '_linkHash',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
