"""idk

Revision ID: 8cbcf216e47b
Revises: 8f37d6a5dedd
Create Date: 2021-12-10 00:29:04.498730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbcf216e47b'
down_revision = '8f37d6a5dedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_link', sa.Column('link', sa.String(length=100), nullable=True))
    op.alter_column('shortened_link', 'linkHash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('shortened_link', '_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_link', sa.Column('_link', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('shortened_link', 'linkHash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('shortened_link', 'link')
    # ### end Alembic commands ###
