"""bingbong

Revision ID: 8f37d6a5dedd
Revises: 6e8e4aa6af69
Create Date: 2021-12-10 00:10:56.107171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f37d6a5dedd'
down_revision = '6e8e4aa6af69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_link', sa.Column('_link', sa.String(length=100), nullable=False))
    op.drop_column('shortened_link', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_link', sa.Column('link', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('shortened_link', '_link')
    # ### end Alembic commands ###
