"""removed non nullable from shortenedlink linkhash

Revision ID: a27049ed88ba
Revises: ed5997d4b977
Create Date: 2021-12-09 20:37:26.079280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27049ed88ba'
down_revision = 'ed5997d4b977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', 'linkHash',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', 'linkHash',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
