"""trytofixshortener1

Revision ID: a2b6fdf31cc4
Revises: 6f3f5c6d11a8
Create Date: 2021-12-09 23:36:17.816437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b6fdf31cc4'
down_revision = '6f3f5c6d11a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', 'link',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('shortened_link', 'linkHash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortened_link', 'linkHash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shortened_link', 'link',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
