"""not nullable

Revision ID: b4a59a7f89ff
Revises: 7cd291f95267
Create Date: 2021-12-09 23:22:27.641847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a59a7f89ff'
down_revision = '7cd291f95267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_link', sa.Column('linkHash', sa.String(length=100), nullable=True))
    op.drop_column('shortened_link', '_linkHash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_link', sa.Column('_linkHash', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('shortened_link', 'linkHash')
    # ### end Alembic commands ###
