"""added shortened link model and enpoints

Revision ID: ed5997d4b977
Revises: 4582f1d132e0
Create Date: 2021-12-08 08:13:12.661512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5997d4b977'
down_revision = '4582f1d132e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('linkHash', sa.String(length=50), nullable=False),
    sa.Column('timeCreated', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortened_link')
    # ### end Alembic commands ###
